# """
# Test Case Generator
# Converts trajectories to executable test cases
# """
# from pathlib import Path
# from typing import List
# import sys

# sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent / 'kimvieware-shared' / 'src'))
# from kimvieware_shared.models import Trajectory

# class TestGenerator:
#     """Generate executable tests from trajectories"""
    
#     def __init__(self, sut_type: str = 'rest_api'):
#         self.sut_type = sut_type
    
#     def generate(self, trajectories: List[Trajectory], output_dir: Path) -> Path:
#         """
#         Generate test file from trajectories
        
#         For REST API services (like auth-service):
#         - Convert path conditions to HTTP requests
#         - Generate pytest test cases
#         """
        
#         output_dir.mkdir(parents=True, exist_ok=True)
#         test_file = output_dir / 'test_generated.py'
        
#         print(f"\n🔧 Generating tests from {len(trajectories)} trajectories...")
        
#         # Generate pytest test cases
#         test_code = self._generate_pytest_code(trajectories)
        
#         test_file.write_text(test_code)
        
#         print(f"✅ Generated: {test_file}")
#         print(f"   {len(trajectories)} test cases")
        
#         return test_file
    
#     def _generate_pytest_code(self, trajectories: List[Trajectory]) -> str:
#         """Generate pytest code for REST API testing"""
        
#         code = '''"""
# Auto-generated test cases from symbolic execution trajectories
# Generated by KIMVIEware Phase 4 Executor
# """
# import pytest
# import requests

# BASE_URL = "http://localhost:8000"

# '''
        
#         # Generate one test per trajectory
#         for i, traj in enumerate(trajectories):
#             test_name = f"test_{traj.path_id}"
            
#             # Parse constraints to determine test scenario
#             # For auth-service: register, login, verify
#             scenario = self._infer_scenario(traj, i)
            
#             code += f'''
# def {test_name}():
#     """Test case for trajectory {traj.path_id}"""
#     # Path condition: {traj.path_condition[:80]}...
#     # Branches covered: {len(traj.branches_covered)}
    
# '''
            
#             if scenario == 'register':
#                 code += f'''    # Test user registration
#     response = requests.post(f"{{BASE_URL}}/auth/register", json={{
#         "email": "test{i}@test.com",
#         "username": "testuser{i}",
#         "password": "Test1234{i}",
#         "full_name": "Test User {i}"
#     }})
#     assert response.status_code in [200, 201, 400]  # Accept success or validation error
# '''
            
#             elif scenario == 'login':
#                 code += f'''    # Test login
#     response = requests.post(f"{{BASE_URL}}/auth/login", json={{
#         "username": "admin",
#         "password": "Admin123!"
#     }})
#     assert response.status_code in [200, 401]  # Accept success or auth error
# '''
            
#             else:  # verify
#                 code += f'''    # Test token verification (with invalid token)
#     response = requests.post(f"{{BASE_URL}}/auth/verify?token=invalid_token_{i}")
#     assert response.status_code in [200, 401]  # Accept success or auth error
# '''
        
#         return code
    
#     def _infer_scenario(self, traj: Trajectory, index: int) -> str:
#         """Infer test scenario from trajectory characteristics"""
        
#         # Simple heuristic based on path characteristics
#         if index % 3 == 0:
#             return 'register'
#         elif index % 3 == 1:
#             return 'login'
#         else:
#             return 'verify'










"""
Test Case Generator - VERSION FINALE AMÉLIORÉE
Génère des tests dynamiques et génériques basés sur l'analyse réelle du SUT.
"""
import re
import sys
from pathlib import Path
from typing import List

# Import des modèles partagés
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent / 'kimvieware-shared' / 'src'))
from kimvieware_shared.models import Trajectory

class TestGenerator:
    """Générateur de tests intelligent et adaptatif"""
    
    def __init__(self, sut_type: str = 'rest_api'):
        self.sut_type = sut_type
    
    def generate(self, trajectories: List[Trajectory], output_dir: Path, sut_url: str = "http://localhost:8000") -> Path:
        """
        Méthode principale de génération.
        Prend en entrée l'URL réelle du SUT pour éviter le hard-coding.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        test_file = output_dir / 'test_generated.py'
        
        print(f"\n🔧 GÉNÉRATION : Création de {len(trajectories)} tests adaptatifs pour {sut_url}")
        
        # Génération du code source du fichier de test
        test_code = self._generate_pytest_code(trajectories, sut_url)
        
        test_file.write_text(test_code)
        
        print(f"✅ Succès : {test_file} généré sans données fictives.")
        return test_file

    def _extract_satisfying_value(self, constraints: List[str], var_name: str) -> str:
        """
        AXE 2 : RÉSOLUTION DE CONTRAINTES
        Analyse les contraintes pour trouver une valeur qui fait passer le test.
        """
        for c in constraints:
            if var_name in c:
                # Cas 1 : Égalité directe (ex: x == 10 ou x == 'admin')
                match_eq = re.search(r"==\s*['\"]?([^'\"]+)['\"]?", c)
                if match_eq:
                    return f"'{match_eq.group(1)}'" if not match_eq.group(1).isdigit() else match_eq.group(1)
                
                # Cas 2 : Comparaison supérieure (ex: score > 15)
                match_gt = re.search(r">\s*(\d+)", c)
                if match_gt:
                    return str(int(match_gt.group(1)) + 1)
                
                # Cas 3 : Comparaison inférieure (ex: age < 18)
                match_lt = re.search(r"<\s*(\d+)", c)
                if match_lt:
                    return str(int(match_lt.group(1)) - 1)
        
        return "'test_val'" # Valeur par défaut si aucune contrainte n'est trouvée

    def _generate_pytest_code(self, trajectories: List[Trajectory], sut_url: str) -> str:
        """Génère un script Pytest générique adapté au contenu des trajectoires."""
        
        # En-tête du fichier de test
        code = f'''"""
Fichier de test généré dynamiquement par KIMVIEware Phase 4.
Cible : {sut_url}
"""
import pytest
import requests

BASE_URL = "{sut_url}"

'''

        for i, traj in enumerate(trajectories):
            test_name = f"test_{traj.path_id}"
            
            # AXE 1 : On déduit l'endpoint (la fonction) depuis la condition de chemin
            # Exemple : si condition = "calculer_note_path_0", l'endpoint est "calculer_note"
            endpoint = traj.path_condition.split('_path_')[0] if '_path_' in traj.path_condition else "process"

            # AXE 2 : Extraction dynamique des variables présentes dans les contraintes
            # On cherche tous les noms de variables (mots avant un opérateur)
            found_vars = set()
            for c in traj.constraints:
                match = re.search(r"(\w+)\s*[><=!]+", c)
                if match:
                    found_vars.add(match.group(1))
            
            # On construit le dictionnaire d'entrée pour le test
            inputs = {v: self._extract_satisfying_value(traj.constraints, v) for v in found_vars}
            # Conversion du dictionnaire en chaîne de caractères pour le code Python
            inputs_str = "{" + ", ".join([f'"{k}": {v}' for k, v in inputs.items()]) + "}"

            # Construction du code de la fonction de test
            code += f'''
def {test_name}():
    """Test dynamique pour le chemin d'exécution {traj.path_id}"""
    
    # Données d'entrée déduites des contraintes symboliques
    payload = {inputs_str}
    
    # Appel dynamique à l'endpoint identifié
    print(f"Appel de {{BASE_URL}}/{endpoint} avec {{payload}}")
    response = requests.post(f"{{BASE_URL}}/{endpoint}", json=payload)
    
    # Oracle de base : Le SUT ne doit pas planter (Erreur 500)
    # et doit répondre de manière cohérente avec le chemin exploré
    assert response.status_code != 500, f"Le SUT a planté pour le chemin {traj.path_id}"
'''
        return code